services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/canadahackers/local_settings.py:/app/canadahackers/local_settings.py:ro
      - type: bind
        source: db_data/db.sqlite3
        target: /app/db.sqlite3

volumes:
  db_data:
