services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./canadahackers/local_settings.py:/app/canadahackers/local/settings.py:ro
      - db_data:/app

volumes:
  db_data:
