services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/canadahackers/local_settings.py:/home/hackers/canadainhackerswebsite/canadahackers/local_settings.py:ro # changed to /metropolis2/ on server
      - db_data:/app

volumes:
  db_data:
