version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /home/hackers/canadainhackerswebsite/canadahackers/local_settings.py
        target: /app/canadahackers/local_settings.py
      - db_data:/app


volumes:
  db_data:
