version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app
      - ./ontariohackers/local_settings.py:./ontariohackers/local_settings.py

volumes:
  db_data:
