version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app
      - /home/hackers/canadainhackerswebsite/ontariohackers/local_settings.py:/app/canadahackers/local_settings.py


volumes:
  db_data:
